# Generated by Django 6.0.7 on 2026-07-14 11:03

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'states',
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='state_name_lower_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('pincode_prefixes', models.CharField(blank=True, help_text='Comma-separated list of pincode prefixes', max_length=100, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('locality_type', models.CharField(choices=[('locality', 'Locality'), ('neighbourhood', 'Neighbourhood'), ('area', 'Area'), ('suburb', 'Suburb'), ('town', 'Town'), ('village', 'Village'), ('ward', 'Ward')], db_index=True, default='locality', max_length=20)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='locations.city')),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'db_table': 'localities',
                'indexes': [models.Index(fields=['city', 'slug'], name='locality_city_slug_idx'), models.Index(django.db.models.functions.text.Lower('name'), name='locality_name_lower_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'slug'], name='city_state_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='city_name_lower_idx'),
        ),
    ]
