# Generated by Django 6.0.7 on 2026-07-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text='Plural label for this category', max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('type', models.CharField(choices=[('category', 'Business Category'), ('specialty', 'Doctor Specialty')], default='category', max_length=20)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated search terms', max_length=300)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class name, for example: fa fa-home', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this category prominently on the home page.')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['type', 'is_active', 'display_order'], name='directory_type_listing_idx'), models.Index(fields=['name'], name='category_name_idx'), models.Index(fields=['slug'], name='category_slug_idx'), models.Index(fields=['aliases'], name='category_alias_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'slug'), name='unique_directory_type_slug'), models.UniqueConstraint(fields=('type', 'name'), name='unique_directory_type_name')],
            },
        ),
    ]
