# Generated by Django 6.0.7 on 2026-07-14 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('geohash', models.CharField(blank=True, max_length=12, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_24_7', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=20)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, limit_choices_to={'type': 'category'}, related_name='businesses', to='directory.category')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.locality')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['locality', 'publication_status', 'is_active'], name='biz_locality_status_idx'), models.Index(fields=['verification_status', 'publication_status', 'is_active'], name='biz_verify_status_idx'), models.Index(fields=['publication_status', 'published_at'], name='biz_published_idx'), models.Index(fields=['latitude', 'longitude', 'geohash'], name='biz_coordinates_idx')],
            },
        ),
    ]
