# Generated by Django 6.0.7 on 2026-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_business'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['geohash'], name='biz_geohash_idx'),
        ),
    ]
