# Generated by Django 6.0.6 on 2026-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
