# Generated by Django 6.0.6 on 2026-07-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('slot', models.PositiveSmallIntegerField(default=1, help_text='Display order of the time slot within the weekday.')),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('note', models.CharField(blank=True, default='', max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='directory.business')),
            ],
            options={
                'verbose_name': 'Business hour',
                'verbose_name_plural': 'Business hours',
                'db_table': 'business_hours',
                'ordering': ['business_id', 'weekday', 'slot', 'opens_at'],
                'indexes': [models.Index(fields=['business', 'weekday'], name='idx_business_hour_business_day'), models.Index(fields=['business', 'weekday', 'opens_at'], name='idx_business_hour_lookup')],
                'constraints': [models.UniqueConstraint(fields=('business', 'weekday', 'slot'), name='uq_business_hour_business_weekday_slot'), models.UniqueConstraint(fields=('business', 'weekday', 'opens_at', 'closes_at'), name='uq_business_hour_exact_time_slot'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='ck_business_hour_valid_weekday'), models.CheckConstraint(condition=models.Q(('slot__gte', 1)), name='ck_business_hour_slot_gte_1'), models.CheckConstraint(condition=models.Q(('opens_at', models.F('closes_at')), _negated=True), name='ck_business_hour_times_not_equal')],
            },
        ),
    ]
