# Generated by Django 6.0.6 on 2026-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_businesshour'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshour',
            name='is_24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
