# Generated by Django 6.0.6 on 2026-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_delete_businesshour'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
