# Generated by Django 6.0.7 on 2026-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_business_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
