# Generated by Django 6.0.7 on 2026-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_business_established_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
