# Generated by Django 6.0.7 on 2026-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_business_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
