# Generated by Django 6.0.7 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_business_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='is_open',
        ),
        migrations.AddField(
            model_name='business',
            name='is_home_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_home_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
