# Generated by Django 6.0.6 on 2026-07-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_testing',
            field=models.BooleanField(default=False),
        ),
    ]
