# Generated by Django 6.0.6 on 2026-07-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
