# Generated by Django 6.0.6 on 2026-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_business_is_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
            },
        ),
    ]
