# Generated by Django 6.0.6 on 2026-07-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_rename_fecility_and_add_business_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.TextField(blank=True),
        ),
    ]
