# Generated by Django 6.0.6 on 2026-07-20 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0027_category_synonyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(choices=[('appointment', 'Doctor Appointment'), ('enquiry', 'General Enquiry')], db_index=True, default='enquiry', max_length=30)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('invalid', 'Invalid')], db_index=True, default='new', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='directory.business')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='directory.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status', '-created_at'], name='directory_l_busines_dbfe0e_idx'), models.Index(fields=['business', 'lead_type', '-created_at'], name='directory_l_busines_b76a77_idx')],
            },
        ),
    ]
